FreeRegisterPage/Models/Account.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeRegisterPage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        public long AccountId { get; set; }
        public short Authority { get; set; }
        [Required(ErrorMessage = "This field is required!")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [DisplayName("UserName")]
        [Required(ErrorMessage = "This field is required!")]
        public string Name { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required!")]
        public string Password { get; set; }
        [DisplayName("Confirm Password")]
        [Required(ErrorMessage = "This field is required!")]
        [Compare("Password")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
        public string RegistrationIP { get; set; }
        public string VerificationToken { get; set; }
        public long ReferrerId { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}

FreeRegisterPage/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeRegisterPage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testEntities : DbContext
    {
        public testEntities()
            : base("name=testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
    }
}

FreeRegisterPage/Models/Model1.Designer.cs
// Generazione del codice predefinita abilitata per il modello 'c:\users\m20\source\repos\FreeRegisterPage\FreeRegisterPage\Models\Model1.edmx'. 
// Per abilitare la generazione del codice legacy, modificare il valore della proprietà della finestra di progettazione 'Strategia di generazione del codice
// su 'Legacy ObjectContext'. Questa proprietà è disponibile nella finestra Proprietà quando il modello è
// aperto nella finestra di progettazione.

// La mancata generazione di classi contesto ed entità può essere dovuta al fatto che è stato creato un modello vuoto, ma
// non è ancora stata scelta la versione di Entity Framework da utilizzare. Per generare una classe contesto e classi entità
// per il modello, aprire il modello nella finestra di progettazione, fare clic con il pulsante destro del mouse nell'area di progettazione e
// selezionare 'Aggiorna modello da database...', 'Genera database da modello...' o 'Aggiungi elemento di generazione
// codice...'.

FreeRegisterPage/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

FreeRegisterPage/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FreeRegisterPage.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

FreeRegisterPage/Controllers/LoginController.cs
using System;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web.Mvc;
using FreeRegisterPage.Models;

namespace EpicNos_Control_Panel.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]

        public string Sha512(string value)
        {
            SHA512 sha = SHA512.Create();
            byte[] data = sha.ComputeHash(Encoding.Default.GetBytes(value));
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < data.Length; i++)
            {
                sb.Append(data[i].ToString("x2"));
            }
            return sb.ToString();
        }

        public ActionResult Athorize(Account account)
        {
            using (testEntities db = new testEntities())
            {
                string pass = Sha512(account.Password);
                var userDetails = db.Account.Where(x => x.Name.Equals(account.Name) && x.Password.Equals(pass)).FirstOrDefault();
                if (userDetails == null)
                {
                    account.LoginErrorMessage = "Incorrect User Credentials.";
                    return View("Index", account);
                }
                else
                {
                    Session["userID"] = userDetails.AccountId;
                    Session["Name"] = userDetails.Name;
                    return RedirectToAction("Index", "Home");
                }
            }
        }

        public ActionResult LogOut()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Login");
        }
    }
}

FreeRegisterPage/Controllers/RegisterController.cs
using FreeRegisterPage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace FreeRegisterPage.Controllers
{
    public class RegisterController : Controller
    {
        [HttpGet]

        public ActionResult Index(int AccountId = 0, byte Authority = 0, string RegistrationIp = null, string VerificationToke = null, int ReferrerId = 0)
        {
            Account account = new Account();
            return View(account);
        }

        [HttpPost]
        public ActionResult Index(Account account)
        {
            using (testEntities db = new testEntities())
            {
                string pass = Sha512(account.Password);
                string pass2 = Sha512(account.ConfirmPassword);
                string password = account.ConfirmPassword;
                if (db.Account.Any(x => x.Name == account.Name))
                {
                    ViewBag.DuplicateMessage = "Username arledy exist.";
                    return View("AddOrEdit", account);
                }
                account.Password = pass;
                account.ConfirmPassword = pass;
                db.Account.Add(account);
                db.SaveChanges();
            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Registration Successful.";
            return View("AddOrEdit", new Account());
        }

        public string Sha512(string value)
        {
            SHA512 sha = SHA512.Create();
            byte[] data = sha.ComputeHash(Encoding.Default.GetBytes(value));
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < data.Length; i++)
            {
                sb.Append(data[i].ToString("x2"));
            }
            return sb.ToString();
        }
    }
}

FreeRegisterPage/Views/Home/Index.cshtml
@if (Session["userID"] == null) //This is a check for block the user access w/o login :D
{
    Response.Redirect("~/Login/Index");
}
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Test Page</title>
</head>
<body>
    <div>
        <h1 style="color:green">This is a simple Home example, you can set what u want here</h1>
    </div>
</body>
</html>

FreeRegisterPage/Views/Login/Index.cshtml
@model FreeRegisterPage.Models.Account
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <style>
        body {
            background-image:url(/resource/bg-site.jpg);
        }

        #login-div {
            position: absolute;
            background-color: white;
            border-radius: 12%;
            left: 40%;
            top: 40%;
            border: 4px solid #000000;
            padding: 15px 20px;
            text-align: center;
            display: inline-block;
        }

        .field-validation-error {
            color: red;
        }
    </style>
</head>
<body>

    <div id="login-div">
        @using (Html.BeginForm("Athorize", "Login", FormMethod.Post))
        {
            <div width="120" height="100" style="vertical-align:middle; text-align:center">
                <img src="~/resource/logo.png" />
            </div>
            <table>
                <tr>
                    <td></td>
                    <td style="text-decoration:solid">Test Login</td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.Name)
                    </td>
                    <td>
                        @Html.EditorFor(model => model.Name)
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Name)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Password)</td>
                    <td>@Html.EditorFor(model => model.Password)</td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Password)</td>
                </tr>
                <tr>
                    <td colspan="2">
                        <label class="field-validation-error">@Html.DisplayFor(model => model.LoginErrorMessage)</label>
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        <label class="field-validation-error">@Html.DisplayFor(model => model.LoginErrorMessage)</label>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" name="Login" value="Login" />
                        <input type="reset" name="Reset" value="Clear" />
                    </td>
                </tr>
            </table>
        }
    </div>
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

FreeRegisterPage/Views/Register/Index.cshtml
@model FreeRegisterPage.Models.Account


<style>
    body {
        background-image: url(/resource/bg-site.jpg);
        width: auto;
        height: auto
    }
    #login-div {
        position: absolute;
        left: 40%;
        top: 40%;
        width: 20%;
        height: 30%;
        text-align: center;
        display: inline-block;
        border: 4px solid #000000;
        padding: 20px 50px;
        border-radius: 12%;
        background-color: white;
        font-size:larger;
    }
</style>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>This is the Page Name</title>
</head>

@using (Html.BeginForm("Index", "Register", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div id="login-div" class="form-horizontal">
        <h4>Register Title</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-2">
                <label class="label-success">@ViewBag.SuccessMessage</label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-2">
                <label class="label-danger">@ViewBag.DuplicateMessage</label>
            </div>
        </div>

        <div>
            <a href="@Url.Action("Index", "Login")">Arledy register? Click Here!</a>
        </div>
    </div>
}



<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>